app = "mycircular-api"

# [build]
#   image = "udlepssoftarch/mycircular-api:latest"

[env]
    JAVA_OPTS = "-XX:MaxRAM=70m"
#    PROFILE = "flyio"

[[services]]
    internal_port = 8080
    protocol = "tcp"

[[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

[[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
